#!/usr/bin/env bash
echo "clean PWD: $PWD"
DXPM_SETUP_PACKAGE_NAME="$1"
if [ "$DXPM_SETUP_PACKAGE_NAME" = "" ]; then
  DXPM_SETUP_PACKAGE_NAME="$($PWD/bin/getprojectname)"
fi
echo "[+] checking if $DXPM_SETUP_PACKAGE_NAME scrach org exists and deleting it"
$PWD/bin/isscratched && sfdx force:org:delete -u "$DXPM_SETUP_PACKAGE_NAME" -p && wait
echo "[+] finished cleaning $DXPM_SETUP_PACKAGE_NAME scrach org"