#!/usr/bin/env bash
DXPM_SETUP_PACKAGE_NAME="$1"
if [ "$DXPM_SETUP_PACKAGE_NAME" = "" ]; then
  DXPM_SETUP_PACKAGE_NAME="$($PWD/bin/getprojectname)"
fi
echo "[+] setting up scratch org $DXPM_SETUP_PACKAGE_NAME"
sfdx force:org:create -f $PWD/config/project-scratch-def.json -a "$DXPM_SETUP_PACKAGE_NAME" -d 1 -w 5 && wait
echo "[+] finished setting up scratch org $DXPM_SETUP_PACKAGE_NAME"
echo "[+] setting scratch org $DXPM_SETUP_PACKAGE_NAME as default locally"
sfdx force:config:set defaultusername=$DXPM_SETUP_PACKAGE_NAME
echo "[+] finished setting scratch org $DXPM_SETUP_PACKAGE_NAME as default username locally"