#!/usr/bin/env bash
export DXPM_SETUP_PACKAGE_NAME="$($PWD/bin/getprojectname)"
export DXPM_CURRENT_PACKAGE_NAME="$DXPM_SETUP_PACKAGE_NAME"
echo "[+] checking if $DXPM_SETUP_PACKAGE_NAME scrach org exists or creating it"
$PWD/bin/isscratched || $PWD/bin/scratch && wait
echo "[+] installing package $DXPM_SETUP_PACKAGE_NAME"
npm install && wait
echo "[+] finished installing package $DXPM_SETUP_PACKAGE_NAME"
export DXPM_CURRENT_PACKAGE_NAME=""
export DXPM_SETUP_PACKAGE_NAME=""