#!/usr/bin/env bash
DXPM_SETUP_PACKAGE_NAME="$1"
if [ "$DXPM_SETUP_PACKAGE_NAME" = "" ]; then
  DXPM_SETUP_PACKAGE_NAME="$($PWD/bin/getprojectname)"
fi
echo "[+] running tests for $DXPM_SETUP_PACKAGE_NAME"
sfdx force:apex:test:run -l RunLocalTests -d ./test_results -r json -w 10 -u "$DXPM_SETUP_PACKAGE_NAME" && wait
echo "[+] finished running tests for $DXPM_SETUP_PACKAGE_NAME"